<!doctype html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title>公司樹狀關係圖</title>
<link rel="stylesheet" href="/static/build.css" />
<?php if (getenv('GOOGLEANALYTICS_ACCOUNT')) { ?>
<script type="text/javascript">
var _gaq = _gaq || [];
_gaq.push(['_setAccount', <?= json_encode(getenv('GOOGLEANALYTICS_ACCOUNT')) ?>]);
_gaq.push(['_trackPageview']);

(function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
})();
</script>
<?php } ?>
</head>
<body>
<form method="GET" action="/">
    查詢統一編號：<input type="text" name="id" value="<?= $this->Escape($this->id) ?>"><button type="submit">查詢</button>
    <a href="/index/about">關於本站資料</a>
    <a href="http://company.g0v.ronny.tw" target="_blank">台灣公司資料查詢</a>
</form>
<?php if ($this->id) { ?>
<span id="status">計算關係中...</span>
<?php } ?>
<div id="parent"></div>
<script src="/static/build.js"></script>
<script>
!function() {
    <?php if (!$this->id) { ?>
        return;
    <?php } ?>
    var d3 = require("ignacioola-d3/d3"),
        InsightsGraph = require("insights");

    d3.json("/index/json?id=<?= intval($this->id) ?>", function(data) {
            var nodes = data[0],
            links = data[1],
            el = document.getElementById("parent");

            graph = new InsightsGraph(el, nodes, links, {
            width: screen.width,
            height: screen.height
            });

            document.getElementById('status').innerHTML = '關係計算完成，畫圖中...';

            graph.on('rendered', function(){
                document.getElementById('status').innerHTML = '';
            });

            graph.tooltip("<div>word: <a href="http://company.g0v.ronny.tw/id/{{no}}" target="_blank">{{text}}({{no}})</a></div><div>count: {{count}}</div> <div>資本額: {{amount}}</div> <div><h3>董監事名單</h3><pre>{{funder}}</pre></div>");
            }, 'json');
}();
</script>
</body>
</html>
