<!doctype html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title><?= $this->unit_title ? $this->escape($this->unit_title . " | ") : "" ?>台灣公司關係圖</title>
<link rel="stylesheet" href="/static/build.css" />
<script src="//code.jquery.com/jquery-1.10.1.min.js"></script>
<?php if (getenv('GOOGLEANALYTICS_ACCOUNT')) { ?>

<script type="text/javascript">
var _gaq = _gaq || [];
_gaq.push(['_setAccount', <?= json_encode(getenv('GOOGLEANALYTICS_ACCOUNT')) ?>]);
_gaq.push(['_trackPageview']);

(function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
})();
</script>
<?php } ?>
</head>
<body>
<form method="GET" action="/" id="query-form">
    查詢統一編號、完整公司名稱、法人名稱或政府機關名稱：<input type="text" name="id" value="<?= $this->Escape($this->id) ?>"><button type="submit">查詢</button>
    <strong><a href="/index/about">關於本站資料</a>(資料更新時間：<?= date('Y-m-d', KeyValue::get('data_updated_at')) ?>)</strong>
    <a href="http://company.g0v.ronny.tw" target="_blank">台灣公司資料查詢</a>
</form>
<?php if ($this->id) { ?>
<span id="status">計算關係中...</span>
<?php } ?>
<div style="position: fixed; border: 2px solid; width: 200px; height: 300px; right: 5px; bottom: 5px">
    <ul id="color-hint">
    </ul>
</div>
<div id="parent"></div>
<script src="/static/insights.standalone.js"></script>
<script>
var color_map = {
    '目標': 'blue',
    '公司': 'lightblue',
    '法人': 'lightgreen',
    '外商': 'yellow',
    '政府': 'orange',
};


for (var cluster in color_map) {
    $('#color-hint').append($('<li></li>').css('background-color', color_map[cluster]).text(cluster));
};

$('#query-form').submit(function(e){
    var input_dom = $('input:text', this);
    var input = input_dom.val();
    var form_dom = $(this);

    if (input.match(/有限公司$/)) {
        e.preventDefault();

        $.get('//company.g0v.ronny.tw/api/search?q=' + encodeURIComponent(input), function(ret){
            if (!ret.found) {
                alert("找不到 " + input + " 的公司統一編號");
                return;
            }

            document.location = '/?id=' + ret.data[0]['統一編號'];
        }, 'json');
    }

});

!function() {
    <?php if (!$this->id) { ?>
        return;
    <?php } ?>

    // https://github.com/ignacioola/insights
    $.get("/index/json?id=<?= urlencode($this->id) ?>", function(data) {
            var nodes = data[0],
            links = data[1],
            el = document.getElementById("parent");

            graph = new Insights(el, nodes, links, {
                width: screen.width,
                height: screen.height,
                colors: color_map
            });

            document.getElementById('status').innerHTML = '關係計算完成，畫圖中...';

            graph.on('rendered', function(){
                document.getElementById('status').innerHTML = '';
            });

            graph.render();

            graph.tooltip("<div>word: {{text}}({{no}})</div><div>資本額: {{amount}}</div> <div><h3>董監事名單</h3><pre>{{funder}}</pre></div>");
            }, 'json');
}();
</script>
</body>
</html>
